//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("SportingSolutions.Udapi.Sdk")]
[assembly: AssemblyDescription("Sporting Solutions Unified Data API Sdk")]
[assembly: AssemblyConfiguration("")]

[assembly: InternalsVisibleTo("SportingSolutions.Udapi.Sdk.Tests")]

