//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("SportingSolutions.Udapi.Sdk")]
[assembly: AssemblyDescription("Sporting Solutions Unified Data API Sdk")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyProduct("SportingSolutions.Udapi.Sdk")]
[assembly: AssemblyCompany("Sporting Solutions Ltd.")]
[assembly: AssemblyCopyright("Copyright (c) Sporting Solutions Ltd. 2017")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("0.0.0.1")]
[assembly: AssemblyFileVersion("0.0.0.1")]
[assembly: AssemblyInformationalVersion("0.0.0.1")]

[assembly: InternalsVisibleTo("SportingSolutions.Udapi.Sdk.Tests")]

